In [110]:
import pandas as pd
from bs4 import BeautifulSoup
import requests
url="https://www.rightmove.co.uk/house-prices/detail.html?locationIdentifier=POSTCODE%5E1040636&searchLocation=CR0+6HU&radius=15.0"

r  = requests.get(url)
data = r.text
html=BeautifulSoup(data)
total_listings=html.find_all("div", {"class": "soldDetails"})

df=pd.DataFrame(columns=('property_address', 'property_price', 'property_type', 'property_date_sold', 'property_no_of_beds'))
i=0
for listings in total_listings:
    if listings.a != None:
        paddress=listings.a.text
    elif listings.div != None:
        paddress=listings.div.text
    
    for listing in listings.find_all('tr'):
        for listing_price in listing.find_all('td', {'class': 'soldPrice'}):
            if listing_price.text != None:
                pprice=listing_price.text.replace('£','').replace(',','')
        for listing_type in listing.find_all('td', {'class': 'soldType'}):
            if listing_type.text != None:
                ptype=listing_type.text
        for listing_date in listing.find_all('td', {'class': 'soldDate'}):
            if listing_date.text != None:
                pdate=listing_date.text
        for listing_beds in listing.find_all('td', {'class': 'noBed'}):
            if listing_beds.text != None:
                pbeds=listing_beds.text
            
        df.loc[i] = [paddress, pprice, ptype, pdate, pbeds]
        i+=1

df.property_price = df.property_price.astype(int)
#df['property_price'] = df['property_price'].map('£{:,.2f}'.format)
df

,property_address,property_price,property_type,property_date_sold,property_no_of_beds
0,"9, Ingle Mews, London, Greater London EC1R 1XG",675000,"Flat, Leasehold, Residential",26 Apr 2019,2 bedrooms
1,"9, Ingle Mews, London, Greater London EC1R 1XG",650000,"Flat, Leasehold, Residential (New Build)",22 Aug 2013,2 bedrooms
2,"45, Rutland Walk, London, Greater London SE6 4LG",450000,"Terraced, Freehold, Residential",26 Apr 2019,3 bedrooms
3,"45, Rutland Walk, London, Greater London SE6 4LG",214000,"Terraced, Freehold, Residential",08 Jan 2010,3 bedrooms
4,"45, Rutland Walk, London, Greater London SE6 4LG",110000,"Terraced, Freehold, Residential",14 Mar 2002,3 bedrooms
5,"45, Rutland Walk, London, Greater London SE6 4LG",56500,"Terraced, Freehold, Residential",19 Feb 1997,3 bedrooms
6,"45, Rutland Walk, London, Greater London SE6 4LG",54000,"Terraced, Freehold, Residential",19 Dec 1995,3 bedrooms
7,"20, Loubet Street, London, Greater London SW17...",390000,"Flat, Leasehold, Residential",26 Apr 2019,2 bedrooms
8,"5, Gordon Avenue, South Croydon, Greater Londo...",360000,"Semi-Detached, Freehold, Residential",26 Apr 2019,
9,"Flat 91, Bridge House, 18, St George Wharf, Lo...",650000,"Flat, Leasehold, Residential",26 Apr 2019,
10,"Flat 91, Bridge House, 18, St George Wharf, Lo...",390000,"Flat, Leasehold, Residential",17 Mar 2006,
11,"Flat 91, Bridge House, 18, St George Wharf, Lo...",226950,"Flat, Leasehold, Residential (New Build)",05 Sep 2000,
12,"15, Dover Park Drive, London, Greater London S...",2436000,"Detached, Freehold, Residential",25 Apr 2019,7 bedrooms
13,"14, Kings Road, Walton-on-thames, Surrey KT12 2RA",975000,"Detached, Freehold, Residential",25 Apr 2019,4 bedrooms
14,"14, Kings Road, Walton-on-thames, Surrey KT12 2RA",660000,"Detached, Freehold, Residential",01 Jun 2018,4 bedrooms
15,"117, Wightman Road, London, Greater London N4 1RJ",720000,"Terraced, Freehold, Residential",25 Apr 2019,4 bedrooms
16,"117, Wightman Road, London, Greater London N4 1RJ",196000,"Terraced, Freehold, Residential",05 Nov 1999,4 bedrooms
17,"117, Wightman Road, London, Greater London N4 1RJ",100000,"Terraced, Freehold, Residential",02 Jul 1999,4 bedrooms
18,"181, Longfellow Road, Worcester Park, Greater ...",530000,"Detached, Freehold, Residential",25 Apr 2019,4 bedrooms
19,"Flat 26, Holst Court, 65, Westminster Bridge R...",618000,"Flat, Leasehold, Residential",25 Apr 2019,
20,"Flat 26, Holst Court, 65, Westminster Bridge R...",157000,"Flat, Leasehold, Residential",30 Jul 1999,
21,"Flat 4, Oak Lodge, Carson Road, London, Greate...",410000,"Flat, Leasehold, Residential",24 Apr 2019,
22,"78, Westerham Drive, Sidcup, Greater London DA...",220000,"Flat, Leasehold, Residential",24 Apr 2019,1 bedroom
23,"78, Westerham Drive, Sidcup, Greater London DA...",173000,"Flat, Leasehold, Residential",19 Mar 2008,1 bedroom
24,"53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ",1010000,"Detached, Freehold, Residential",24 Apr 2019,4 bedrooms
25,"53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ",770000,"Detached, Freehold, Residential",05 Sep 2006,4 bedrooms
26,"53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ",675000,"Detached, Freehold, Residential",08 Oct 2003,4 bedrooms
27,"53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ",265000,"Detached, Freehold, Residential",25 Oct 1996,4 bedrooms
28,"39, Christ Church Mount, Epsom, Surrey KT19 8LZ",850000,"Detached, Freehold, Residential",24 Apr 2019,3 bedrooms
29,"103, Wentworth Way, South Croydon, Greater Lon...",480000,"Semi-Detached, Freehold, Residential",24 Apr 2019,
30,"27, Parklawn Avenue, Epsom, Surrey KT18 7SJ",635000,"Semi-Detached, Freehold, Residential",24 Apr 2019,3 bedrooms
31,"27, Parklawn Avenue, Epsom, Surrey KT18 7SJ",360000,"Semi-Detached, Freehold, Residential",16 Aug 2012,3 bedrooms
32,"8, Ewelands, Horley, Surrey RH6 9XD",390000,"Detached, Freehold, Residential",24 Apr 2019,3 bedrooms
33,"8, Ewelands, Horley, Surrey RH6 9XD",325000,"Detached, Freehold, Residential",21 Mar 2014,3 bedrooms
34,"8, Ewelands, Horley, Surrey RH6 9XD",136000,"Detached, Freehold, Residential",09 Aug 1999,3 bedrooms
35,"Flat 2, Harrison Bell House, 2a, Oak Crescent,...",250000,"Flat, Leasehold, Residential",24 Apr 2019,
36,"Flat 2, Harrison Bell House, 2a, Oak Crescent,...",210000,"Flat, Leasehold, Residential (New Build)",17 Dec 2007,
37,"14, Charlwood Place, Reigate, Surrey RH2 9BA",600000,"Terraced, Freehold, Residential",24 Apr 2019,3 bedrooms
38,"14, Charlwood Place, Reigate, Surrey RH2 9BA",540000,"Terraced, Freehold, Residential",15 Aug 2014,3 bedrooms
39,"15, Monkleigh Road, Morden, Greater London SM4...",560000,"Semi-Detached, Freehold, Residential",24 Apr 2019,3 bedrooms
40,"18, Holden Street, London, Greater London SW11...",930000,"Terraced, Freehold, Residential",24 Apr 2019,3 bedrooms
41,"18, Holden Street, London, Greater London SW11...",875000,"Terraced, Freehold, Residential",04 Jun 2014,3 bedrooms
42,"18, Holden Street, London, Greater London SW11...",330000,"Terraced, Freehold, Residential",17 Nov 2004,3 bedrooms
43,"18, Holden Street, London, Greater London SW11...",286000,"Terraced, Freehold, Residential",29 Sep 2000,3 bedrooms
44,"12, Hartington Road, London, Greater London E1...",735000,"Terraced, Freehold, Residential",24 Apr 2019,
45,"12, Hartington Road, London, Greater London E1...",89650,"Terraced, Freehold, Residential",29 Nov 1999,
46,"1, Lyndon Avenue, Wallington, Greater London S...",550000,"Detached, Freehold, Residential",24 Apr 2019,3 bedrooms
47,"1, Lyndon Avenue, Wallington, Greater London S...",300000,"Detached, Freehold, Residential",07 Dec 2007,3 bedrooms
48,"30, Oaklands Avenue, Isleworth, Greater London...",775000,"Terraced, Freehold, Residential",24 Apr 2019,
49,"40, Allen Road, Beckenham, Greater London BR3 4NP",479000,"Terraced, Freehold, Residential",24 Apr 2019,

In [109]:
property_address=df.groupby('property_address')
most_expensive_property_per_address=property_address['property_address','property_price'].max().sort_values(by=['property_price'], ascending=False)
most_expensive_property_per_address

,property_address,property_price
property_address,,
"15, Dover Park Drive, London, Greater London SW15 5BT","15, Dover Park Drive, London, Greater London S...",2436000
"53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ","53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ",1010000
"14, Kings Road, Walton-on-thames, Surrey KT12 2RA","14, Kings Road, Walton-on-thames, Surrey KT12 2RA",975000
"18, Holden Street, London, Greater London SW11 5UP","18, Holden Street, London, Greater London SW11...",930000
"39, Christ Church Mount, Epsom, Surrey KT19 8LZ","39, Christ Church Mount, Epsom, Surrey KT19 8LZ",850000
"12, Hartington Road, London, Greater London E17 8AT","12, Hartington Road, London, Greater London E1...",735000
"117, Wightman Road, London, Greater London N4 1RJ","117, Wightman Road, London, Greater London N4 1RJ",720000
"9, Ingle Mews, London, Greater London EC1R 1XG","9, Ingle Mews, London, Greater London EC1R 1XG",675000
"Flat 91, Bridge House, 18, St George Wharf, London, Greater London SW8 2LQ","Flat 91, Bridge House, 18, St George Wharf, Lo...",650000
"27, Parklawn Avenue, Epsom, Surrey KT18 7SJ","27, Parklawn Avenue, Epsom, Surrey KT18 7SJ",635000
"Flat 26, Holst Court, 65, Westminster Bridge Road, London, Greater London SE1 7JQ","Flat 26, Holst Court, 65, Westminster Bridge R...",618000
"14, Charlwood Place, Reigate, Surrey RH2 9BA","14, Charlwood Place, Reigate, Surrey RH2 9BA",600000
"15, Monkleigh Road, Morden, Greater London SM4 4EN","15, Monkleigh Road, Morden, Greater London SM4...",560000
"1, Lyndon Avenue, Wallington, Greater London SM6 7JT","1, Lyndon Avenue, Wallington, Greater London S...",550000
"181, Longfellow Road, Worcester Park, Greater London KT4 8BA","181, Longfellow Road, Worcester Park, Greater ...",530000
"103, Wentworth Way, South Croydon, Greater London CR2 9EZ","103, Wentworth Way, South Croydon, Greater Lon...",480000
"40, Allen Road, Beckenham, Greater London BR3 4NP","40, Allen Road, Beckenham, Greater London BR3 4NP",479000
"45, Rutland Walk, London, Greater London SE6 4LG","45, Rutland Walk, London, Greater London SE6 4LG",450000
"Flat 4, Oak Lodge, Carson Road, London, Greater London SE21 8HS","Flat 4, Oak Lodge, Carson Road, London, Greate...",410000
"20, Loubet Street, London, Greater London SW17 9HD","20, Loubet Street, London, Greater London SW17...",390000
"8, Ewelands, Horley, Surrey RH6 9XD","8, Ewelands, Horley, Surrey RH6 9XD",390000
"5, Gordon Avenue, South Croydon, Greater London CR2 0QN","5, Gordon Avenue, South Croydon, Greater Londo...",360000
"12, Norfolk Close, London, Greater London N2 8ET","12, Norfolk Close, London, Greater London N2 8ET",348000
"Flat 2, Harrison Bell House, 2a, Oak Crescent, London, Greater London E16 4QL","Flat 2, Harrison Bell House, 2a, Oak Crescent,...",250000
"78, Westerham Drive, Sidcup, Greater London DA15 9NR","78, Westerham Drive, Sidcup, Greater London DA...",220000

In [66]:
properties_per_address=df['property_address'].value_counts()
properties_per_address

45, Rutland Walk, London, Greater London SE6 4LG                                     5
53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ                                         4
18, Holden Street, London, Greater London SW11 5UP                                   4
Flat 91, Bridge House, 18, St George Wharf, London, Greater London SW8 2LQ           3
8, Ewelands, Horley, Surrey RH6 9XD                                                  3
117, Wightman Road, London, Greater London N4 1RJ                                    3
12, Hartington Road, London, Greater London E17 8AT                                  2
27, Parklawn Avenue, Epsom, Surrey KT18 7SJ                                          2
14, Charlwood Place, Reigate, Surrey RH2 9BA                                         2
1, Lyndon Avenue, Wallington, Greater London SM6 7JT                                 2
78, Westerham Drive, Sidcup, Greater London DA15 9NR                                 2
Flat 26, Holst Court, 65, Westminster Bridge Road, London, Greater London SE1 7JQ    2
Flat 2, Harrison Bell House, 2a, Oak Crescent, London, Greater London E16 4QL        2
14, Kings Road, Walton-on-thames, Surrey KT12 2RA                                    2
9, Ingle Mews, London, Greater London EC1R 1XG                                       2
181, Longfellow Road, Worcester Park, Greater London KT4 8BA                         1
20, Loubet Street, London, Greater London SW17 9HD                                   1
15, Monkleigh Road, Morden, Greater London SM4 4EN                                   1
5, Gordon Avenue, South Croydon, Greater London CR2 0QN                              1
39, Christ Church Mount, Epsom, Surrey KT19 8LZ                                      1
Flat 4, Oak Lodge, Carson Road, London, Greater London SE21 8HS                      1
103, Wentworth Way, South Croydon, Greater London CR2 9EZ                            1
30, Oaklands Avenue, Isleworth, Greater London TW7 5PX                               1
12, Norfolk Close, London, Greater London N2 8ET                                     1
15, Dover Park Drive, London, Greater London SW15 5BT                                1
Name: property_address, dtype: int64

In [71]:
property_address=df.groupby(['property_address','property_no_of_beds']).size()
property_address

property_address                                                                   property_no_of_beds
1, Lyndon Avenue, Wallington, Greater London SM6 7JT                               3 bedrooms             2
103, Wentworth Way, South Croydon, Greater London CR2 9EZ                                                 1
117, Wightman Road, London, Greater London N4 1RJ                                  4 bedrooms             3
12, Hartington Road, London, Greater London E17 8AT                                                       2
12, Norfolk Close, London, Greater London N2 8ET                                   3 bedrooms             1
14, Charlwood Place, Reigate, Surrey RH2 9BA                                       3 bedrooms             2
14, Kings Road, Walton-on-thames, Surrey KT12 2RA                                  4 bedrooms             2
15, Dover Park Drive, London, Greater London SW15 5BT                              7 bedrooms             1
15, Monkleigh Road, Morden, Greater London SM4 4EN                                 3 bedrooms             1
18, Holden Street, London, Greater London SW11 5UP                                 3 bedrooms             4
181, Longfellow Road, Worcester Park, Greater London KT4 8BA                       4 bedrooms             1
20, Loubet Street, London, Greater London SW17 9HD                                 2 bedrooms             1
27, Parklawn Avenue, Epsom, Surrey KT18 7SJ                                        3 bedrooms             2
30, Oaklands Avenue, Isleworth, Greater London TW7 5PX                                                    1
39, Christ Church Mount, Epsom, Surrey KT19 8LZ                                    3 bedrooms             1
45, Rutland Walk, London, Greater London SE6 4LG                                   3 bedrooms             5
5, Gordon Avenue, South Croydon, Greater London CR2 0QN                                                   1
53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ                                       4 bedrooms             4
78, Westerham Drive, Sidcup, Greater London DA15 9NR                               1 bedroom              2
8, Ewelands, Horley, Surrey RH6 9XD                                                3 bedrooms             3
9, Ingle Mews, London, Greater London EC1R 1XG                                     2 bedrooms             2
Flat 2, Harrison Bell House, 2a, Oak Crescent, London, Greater London E16 4QL                             2
Flat 26, Holst Court, 65, Westminster Bridge Road, London, Greater London SE1 7JQ                         2
Flat 4, Oak Lodge, Carson Road, London, Greater London SE21 8HS                                           1
Flat 91, Bridge House, 18, St George Wharf, London, Greater London SW8 2LQ                                3
dtype: int64

In [108]:
property_address=df.groupby('property_address')
avg_price_of_property_per_address=property_address['property_address','property_price'].mean().sort_values(by=['property_price'], ascending=False)
avg_price_of_property_per_address

                                                    property_price
property_address
15, Dover Park Drive, London, Greater London SW...    2.436000e+06
39, Christ Church Mount, Epsom, Surrey KT19 8LZ       8.500000e+05
14, Kings Road, Walton-on-thames, Surrey KT12 2RA     8.175000e+05
53, Chipstead Lane, Sevenoaks, Kent TN13 2AJ          6.800000e+05
9, Ingle Mews, London, Greater London EC1R 1XG        6.625000e+05
18, Holden Street, London, Greater London SW11 5UP    6.052500e+05
14, Charlwood Place, Reigate, Surrey RH2 9BA          5.700000e+05
15, Monkleigh Road, Morden, Greater London SM4 4EN    5.600000e+05
181, Longfellow Road, Worcester Park, Greater L...    5.300000e+05
27, Parklawn Avenue, Epsom, Surrey KT18 7SJ           4.975000e+05
103, Wentworth Way, South Croydon, Greater Lond...    4.800000e+05
40, Allen Road, Beckenham, Greater London BR3 4NP     4.790000e+05
1, Lyndon Avenue, Wallington, Greater London SM...    4.250000e+05
Flat 91, Bridge House, 18, St George Wharf, Lon...    4.223167e+05
12, Hartington Road, London, Greater London E17...    4.123250e+05
Flat 4, Oak Lodge, Carson Road, London, Greater...    4.100000e+05
20, Loubet Street, London, Greater London SW17 9HD    3.900000e+05
Flat 26, Holst Court, 65, Westminster Bridge Ro...    3.875000e+05
5, Gordon Avenue, South Croydon, Greater London...    3.600000e+05
12, Norfolk Close, London, Greater London N2 8ET      3.480000e+05
117, Wightman Road, London, Greater London N4 1RJ     3.386667e+05
8, Ewelands, Horley, Surrey RH6 9XD                   2.836667e+05
Flat 2, Harrison Bell House, 2a, Oak Crescent, ...    2.300000e+05
78, Westerham Drive, Sidcup, Greater London DA1...    1.965000e+05
45, Rutland Walk, London, Greater London SE6 4LG      1.769000e+05